Repository AY2425S2-CS2103T-T08-4/tp, pull requests merged in 2025-03, with the labels that each got.

#8 docs: Add Warren's photo to docs
  docs/images/desuclub.png
Labels: type.Task, severity.VeryLow

#20 docs: Update AboutUs.md
  docs/AboutUs.md
Labels: type.Task, severity.VeryLow

#28 docs: Add correct name for photo
  docs/AboutUs.md
  docs/images/desu-club.png
Labels: type.Task, severity.VeryLow

#31 feat: Add Advay's photo
  docs/images/advaypakhale.jpg
Labels: type.Task, priority.Low

#35 task: Add Individual Photo
  .gitattributes
  copyright.txt
  docs/images/mingyuan03.png
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, severity.VeryLow

#27 docs: Add initial version of dev guide
  docs/DeveloperGuide.md
Labels: type.Task, severity.VeryLow

#5 Fix checkstyle warnings and critical LogsCenter bug
  src/main/java/seedu/address/commons/core/Version.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, severity.Low

#11 chore: Update README.md to TalentMatch
  README.md
Labels: type.Task, severity.VeryLow

#43 feat: Branch new v0
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Bug

#44 Branch fix readme ci
  README.md
Labels: type.Task, priority.Low

#46 docs: Add TalentMatch to all guides
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/advaypakhale.png
  docs/index.md
Labels: type.Task, priority.Low

#50 feat: Add skills and corresponding UI for TalentMatch
  .gitignore
  build.gradle
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/util/IconUtil.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/ui/util/IconUtilTest.java
Labels: type.Enhancement, severity.High

#77 Feat: Add ObservableListDeserializer and 3 Job functionalities
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/commons/util/ObservableListDeserializer.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
  src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteJobCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ApplicationsManager.java
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/application/UniqueApplicationList.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/JobAddress.java
  src/main/java/seedu/address/model/job/JobCompany.java
  src/main/java/seedu/address/model/job/JobRounds.java
  src/main/java/seedu/address/model/job/JobSkills.java
  src/main/java/seedu/address/model/job/JobTitle.java
  src/main/java/seedu/address/model/job/JobType.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
  src/main/java/seedu/address/model/job/exceptions/DuplicateJobException.java
  src/main/java/seedu/address/model/job/exceptions/DuplicateSkillException.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/main/java/seedu/address/storage/JsonAdaptedJob.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium

#84 feat: Add EditJobCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
  src/main/java/seedu/address/logic/commands/EditJobCommand.java
  src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteJobCommandParser.java
  src/main/java/seedu/address/logic/parser/EditJobCommandParser.java
  src/main/java/seedu/address/model/job/Job.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteJobCommandTest.java
  src/test/java/seedu/address/testutil/JobBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium

#96 Feat: CUD ApplicationCommands
  build.gradle
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/AdvanceApplicationCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteApplicationCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
  src/main/java/seedu/address/logic/commands/EditJobCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AdvanceApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ApplicationsManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/application/ApplicationStatus.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/JobAddress.java
  src/main/java/seedu/address/model/job/JobCompany.java
  src/main/java/seedu/address/model/job/JobRounds.java
  src/main/java/seedu/address/model/job/JobSkills.java
  src/main/java/seedu/address/model/job/JobTitle.java
  src/main/java/seedu/address/model/job/JobType.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Degree.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/School.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedJob.java
  src/main/java/seedu/address/ui/JobCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/AddApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AdvanceApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteJobCommandTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/JobBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium, severity.High

#101 Add Branch command history
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/EditJobCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/SetCompanyCommand.java
  src/main/java/seedu/address/logic/commands/SwitchViewCommand.java
  src/main/java/seedu/address/logic/parser/EditJobCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/DoublyLinkedList.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/CompanyAddress.java
  src/main/java/seedu/address/model/company/CompanyName.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/storage/JsonAdaptedJob.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/JobCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/JobListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/JobBuilder.java
  src/test/java/seedu/address/testutil/JobBuilderFX.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium

#119 feat: Make job view the primary view, and add ApplicationStatusPredicate
  src/main/java/seedu/address/model/application/ApplicationStatusPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement, priority.Medium

#120 Remove JobType
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/EditJobCommand.java
  src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditJobCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/JobType.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedJob.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/JobBuilder.java
  src/test/java/seedu/address/testutil/JobBuilderFX.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#122 Decouple commands
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/ClearViewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditJobCommand.java
  src/main/java/seedu/address/logic/commands/FindAppCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindJobCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListJobCommand.java
  src/main/java/seedu/address/logic/commands/ViewJobCommand.java
  src/main/java/seedu/address/logic/commands/ViewPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/JobListPanel.java
  src/main/java/seedu/address/ui/JobSpecificStatsPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticsChartPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindAppCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/SwitchViewCommandTest.java
Labels: type.Enhancement, priority.High
