Repository AY2425S2-CS2103T-T08-4/tp, pull requests merged in 2025-04, with the labels that each got.

#124 Feat: Refactor Application Commands
  build.gradle
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/AdvanceApplicationCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApplicationCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditJobCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindAppCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindJobCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListJobCommand.java
  src/main/java/seedu/address/logic/commands/SwitchViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewJobCommand.java
  src/main/java/seedu/address/logic/commands/ViewPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/AdvanceApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/FindAppCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ApplicationsManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/application/ApplicationStatus.java
  src/main/java/seedu/address/model/application/UniqueApplicationList.java
  src/main/java/seedu/address/model/job/JobTitle.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteJobCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Story, priority.Medium, severity.Medium

#125 feat: Modify internal representation of command DLL to use java collections
  src/main/java/seedu/address/model/DoublyLinkedList.java
Labels: type.Task, priority.High, severity.High

#136 fix: Standardise command box instructions
  src/main/java/seedu/address/logic/commands/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/commands/AdvanceApplicationCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApplicationCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditJobCommand.java
  src/main/java/seedu/address/logic/commands/FindAppCommand.java
  src/main/java/seedu/address/logic/commands/ViewJobCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: alpha-bug

#150 Fix storage bugs
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, type.Bug, severity.High, alpha-bug

#153 Fix editjob
  src/main/java/seedu/address/logic/commands/EditJobCommand.java
  src/main/java/seedu/address/model/job/UniqueJobList.java
Labels: priority.High, type.Bug, severity.High, alpha-bug

#155 Add more descriptive messages for when find returns no results
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindAppCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindJobCommand.java
  src/main/java/seedu/address/logic/commands/SwitchViewCommand.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: priority.High, type.Bug, severity.High, alpha-bug

#156 Fix: modify test for find command
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#161 Fix job parsers
  src/main/java/seedu/address/logic/commands/AddJobCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Degree.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/School.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug

#162 Various hotfixes
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
  src/main/java/seedu/address/logic/parser/AdvanceApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteJobCommandParser.java
  src/main/java/seedu/address/logic/parser/FindAppCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: priority.High, type.Bug, severity.High

#166 Doc: Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img.png
  docs/img_1.png
  docs/img_2.png
  docs/img_3.png
  docs/img_4.png
  docs/img_5.png
  docs/img_6.png
Labels: type.Task, priority.Medium
